---
-- 由 utils.GenCodeUtil.genPbcsFile 生成,不要手动修改
--

local pbc = require('protobuf')
local CCReadFile = CCReadFile

module('prototol.pbcs')


pbc.register( CCReadFile('scripts/protocol/pbc/biwu/biwu.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/buff/buff.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/chat/chat.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/chenmi/chenmi.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/dailytask/dailytask.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/duobao/duobao.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/fight/fight.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/fjpartner/fjpartner.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/friend/friend.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/fuben/fuben.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/giftcode/giftcode.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/guide/guide.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/hero/hero.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/hongmeng/hongmeng.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/item/item.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/item/item_streng.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/jianwen/jianwen.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/jiejiao/jiejiao.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/juxian/juxian.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/login/login.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/loginbonus/loginbonus.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/mail/mail.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/migong/migong.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/obt/obt.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/onlinebonus/onlinebonus.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/partner/partner.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/partunyuan/partunyuan.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/partybase/partybase.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/parupstar/parupstar.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/physicalbonus/physicalbonus.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/phyvigor/phyvigor.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/ptduijie/ptduijie.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/randomev/randomev.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/ranklist/ranklist.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/secret/secret.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/shilian/shilian.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/shop/shop.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/signin/signin.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/sumloginbonus/sumloginbonus.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/task/task.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/test/test.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/treasure/treasure.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/ui/ui.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/vip/vip.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/wizcmd/wizcmd.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/worldboss/worldboss.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/wulin/wulin.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/xiulian/xiulian.pb') )
pbc.register( CCReadFile('scripts/protocol/pbc/zhenqi/zhenqi.pb') )
