--- 
-- 连续登陆奖励表
-- 该文件为代码自动生成，请不要手动修改
-- @module xls.LoginBonusXls
-- 

module("xls.LoginBonusXls")

--- 
-- @type LoginBonusXls
-- @field	#number	RewardType	类型	 
-- @field	#number	LoginDay	登陆天数	 
-- @field	#number	No	奖励序号	 
-- @field	#number	RewardIcon	图标	 
-- @field	#number	RewardRare	稀有度	 
-- @field	#string	RewardName	奖励名称	 
-- 

--- 
-- LoginBonusXls
-- @field [parent=#xls.LoginBonusXls] #LoginBonusXls LoginBonusXls
-- 

--- 
-- data
-- @field [parent=#xls.LoginBonusXls] #table data  -> @{LoginBonusXls}表
-- 
data = 
{
	[1] = {
		["RewardType"] = 2,
		["LoginDay"] = 1,
		["No"] = 1,
		["RewardIcon"] = 4000031,
		["RewardRare"] = 2,
		["RewardName"] = "绿品侠客",
	},
	[2] = {
		["RewardType"] = 2,
		["LoginDay"] = 1,
		["No"] = 2,
		["RewardIcon"] = 4000032,
		["RewardRare"] = 3,
		["RewardName"] = "蓝品侠客",
	},
	[3] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 3,
		["RewardIcon"] = 4000023,
		["RewardRare"] = 2,
		["RewardName"] = "绿品武功",
	},
	[4] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 4,
		["RewardIcon"] = 4000024,
		["RewardRare"] = 3,
		["RewardName"] = "蓝品武功",
	},
	[5] = {
		["RewardType"] = 1,
		["LoginDay"] = 1,
		["No"] = 5,
		["RewardIcon"] = 4000027,
		["RewardRare"] = 1,
		["RewardName"] = "绿品装备",
	},
	[6] = {
		["RewardType"] = 1,
		["LoginDay"] = 1,
		["No"] = 6,
		["RewardIcon"] = 4000028,
		["RewardRare"] = 2,
		["RewardName"] = "蓝品装备",
	},
	[7] = {
		["RewardType"] = 2,
		["LoginDay"] = 1,
		["No"] = 7,
		["RewardIcon"] = 4000032,
		["RewardRare"] = 3,
		["RewardName"] = "蓝品侠客",
	},
	[8] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 8,
		["RewardIcon"] = 4000024,
		["RewardRare"] = 3,
		["RewardName"] = "蓝品武功",
	},
	[9] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 9,
		["RewardIcon"] = 4000008,
		["RewardRare"] = 2,
		["RewardName"] = "银两（少）",
	},
	[10] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 10,
		["RewardIcon"] = 4000009,
		["RewardRare"] = 3,
		["RewardName"] = "银两（中）",
	},
	[11] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 11,
		["RewardIcon"] = 4000010,
		["RewardRare"] = 4,
		["RewardName"] = "银两（多）",
	},
	[12] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 12,
		["RewardIcon"] = 4000014,
		["RewardRare"] = 2,
		["RewardName"] = "元宝 +5",
	},
	[13] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 13,
		["RewardIcon"] = 4000015,
		["RewardRare"] = 3,
		["RewardName"] = "元宝 +10",
	},
	[14] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 14,
		["RewardIcon"] = 4000007,
		["RewardRare"] = 4,
		["RewardName"] = "小还丹",
	},
	[15] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 15,
		["RewardIcon"] = 4000017,
		["RewardRare"] = 2,
		["RewardName"] = "体力 +2",
	},
	[16] = {
		["RewardType"] = 3,
		["LoginDay"] = 1,
		["No"] = 16,
		["RewardIcon"] = 4000020,
		["RewardRare"] = 2,
		["RewardName"] = "精力 +2",
	},
	[17] = {
		["RewardType"] = 1,
		["LoginDay"] = 2,
		["No"] = 1,
		["RewardIcon"] = 4000029,
		["RewardRare"] = 3,
		["RewardName"] = "紫品装备",
	},
	[18] = {
		["RewardType"] = 2,
		["LoginDay"] = 2,
		["No"] = 2,
		["RewardIcon"] = 4000032,
		["RewardRare"] = 3,
		["RewardName"] = "蓝品侠客",
	},
	[19] = {
		["RewardType"] = 2,
		["LoginDay"] = 2,
		["No"] = 3,
		["RewardIcon"] = 4000033,
		["RewardRare"] = 4,
		["RewardName"] = "紫品侠客",
	},
	[20] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 4,
		["RewardIcon"] = 4000024,
		["RewardRare"] = 3,
		["RewardName"] = "蓝品武功",
	},
	[21] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 5,
		["RewardIcon"] = 4000025,
		["RewardRare"] = 4,
		["RewardName"] = "紫品武功",
	},
	[22] = {
		["RewardType"] = 1,
		["LoginDay"] = 2,
		["No"] = 6,
		["RewardIcon"] = 4000029,
		["RewardRare"] = 3,
		["RewardName"] = "紫品装备",
	},
	[23] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 7,
		["RewardIcon"] = 4000008,
		["RewardRare"] = 1,
		["RewardName"] = "银两（少）",
	},
	[24] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 8,
		["RewardIcon"] = 4000009,
		["RewardRare"] = 2,
		["RewardName"] = "银两（中）",
	},
	[25] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 9,
		["RewardIcon"] = 4000010,
		["RewardRare"] = 3,
		["RewardName"] = "银两（多）",
	},
	[26] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 10,
		["RewardIcon"] = 4000007,
		["RewardRare"] = 4,
		["RewardName"] = "小还丹",
	},
	[27] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 11,
		["RewardIcon"] = 4000014,
		["RewardRare"] = 3,
		["RewardName"] = "元宝 +15",
	},
	[28] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 12,
		["RewardIcon"] = 4000015,
		["RewardRare"] = 4,
		["RewardName"] = "元宝 +20",
	},
	[29] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 13,
		["RewardIcon"] = 4000018,
		["RewardRare"] = 3,
		["RewardName"] = "体力 +4",
	},
	[30] = {
		["RewardType"] = 3,
		["LoginDay"] = 2,
		["No"] = 14,
		["RewardIcon"] = 4000021,
		["RewardRare"] = 3,
		["RewardName"] = "精力 +4",
	},
	[31] = {
		["RewardType"] = 2,
		["LoginDay"] = 3,
		["No"] = 1,
		["RewardIcon"] = 4000033,
		["RewardRare"] = 4,
		["RewardName"] = "紫品侠客",
	},
	[32] = {
		["RewardType"] = 2,
		["LoginDay"] = 3,
		["No"] = 2,
		["RewardIcon"] = 4000034,
		["RewardRare"] = 5,
		["RewardName"] = "橙品侠客",
	},
	[33] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 3,
		["RewardIcon"] = 4000025,
		["RewardRare"] = 4,
		["RewardName"] = "紫品武功",
	},
	[34] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 4,
		["RewardIcon"] = 4000026,
		["RewardRare"] = 5,
		["RewardName"] = "橙品武功",
	},
	[35] = {
		["RewardType"] = 1,
		["LoginDay"] = 3,
		["No"] = 5,
		["RewardIcon"] = 4000030,
		["RewardRare"] = 4,
		["RewardName"] = "橙品装备",
	},
	[36] = {
		["RewardType"] = 1,
		["LoginDay"] = 3,
		["No"] = 6,
		["RewardIcon"] = 4000030,
		["RewardRare"] = 4,
		["RewardName"] = "橙品装备",
	},
	[37] = {
		["RewardType"] = 2,
		["LoginDay"] = 3,
		["No"] = 7,
		["RewardIcon"] = 4000032,
		["RewardRare"] = 3,
		["RewardName"] = "蓝品侠客",
	},
	[38] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 8,
		["RewardIcon"] = 4000024,
		["RewardRare"] = 3,
		["RewardName"] = "蓝品武功",
	},
	[39] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 9,
		["RewardIcon"] = 4000008,
		["RewardRare"] = 2,
		["RewardName"] = "银两（少）",
	},
	[40] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 10,
		["RewardIcon"] = 4000009,
		["RewardRare"] = 3,
		["RewardName"] = "银两（中）",
	},
	[41] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 11,
		["RewardIcon"] = 4000010,
		["RewardRare"] = 4,
		["RewardName"] = "银两（多）",
	},
	[42] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 12,
		["RewardIcon"] = 4000007,
		["RewardRare"] = 4,
		["RewardName"] = "小还丹",
	},
	[43] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 13,
		["RewardIcon"] = 4000004,
		["RewardRare"] = 5,
		["RewardName"] = "大还丹",
	},
	[44] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 14,
		["RewardIcon"] = 4000015,
		["RewardRare"] = 4,
		["RewardName"] = "元宝 +25",
	},
	[45] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 15,
		["RewardIcon"] = 4000016,
		["RewardRare"] = 5,
		["RewardName"] = "元宝 +30",
	},
	[46] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 16,
		["RewardIcon"] = 4000019,
		["RewardRare"] = 4,
		["RewardName"] = "体力 +6",
	},
	[47] = {
		["RewardType"] = 3,
		["LoginDay"] = 3,
		["No"] = 17,
		["RewardIcon"] = 4000022,
		["RewardRare"] = 4,
		["RewardName"] = "精力 +6",
	},
}